spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/data_jpa
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        show-sql: true